language: node_js
node_js: 'node'

cache:
  directories:
    - node_modules

stages:
  - name: test
    if: (NOT type IN (push))
  - deploy

jobs:
  include:
    - stage: test
      script: npm run test
    - stage: deploy
      deploy:
        provider: script
        script: bash scripts/deploy.sh
        on:
          tags: true

# language: node_js
# node_js: 'node'

# cache:
#   directories:
#     - node_modules

# jobs:
#   include:
#     - stage: install
#       name: 'Npm install and lerna bootstrap'
#       script:
#         - npm install
#         - npm run init
#     - stage: lint
#       name: 'Lint'
#       script: npm run lint
#     - stage: build
#       name: 'Build'
#       script: npm run build
#     - stage: test
#       name: 'Test'
#       script: npm run test:unit