language: node_js
node_js: 'node'

cache:
  directories:
    - node_modules

stages:
  - name: test
    if: (NOT (tag IS blank))
  - deploy

jobs:
  include:
    - stage: test
      script: npm run test
    - stage: deploy
      deploy:
        provider: script
        script: bash scripts/deploy.sh
        on:
          tags: true