language: node_js
node_js: 'node'

cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: testing
      if: branch = master
      script: npm run test
    - stage: deploy
      deploy:
        provider: script
        script: bash scripts/deploy.sh
        on:
          tags: true