language: node_js
node_js: 'node'

cache:
  directories:
    - node_modules

stages:
  - name: deploy
    if: tag IS present
  - name: testing
    if: type = pull_request

jobs:
  include:
    - stage: testing
      if: type = pull_request
      script: npm run test
    - stage: deploy
      if: tag IS present
      script: echo 'Deploying $TRAVIS_TAG'
      deploy:
        provider: script
        script: bash scripts/deploy.sh
        on:
          tags: true