language: node_js
node_js: 'node'

cache:
  directories:
    - node_modules

stages:
  - name: testing
    if: type = pull_request

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    tags: true

jobs:
  include:
    - stage: testing
      if: type = pull_request
      script: npm run test