language: node_js
node_js: 'node'

cache:
  directories:
    - node_modules

stages:
  - deploy
  - name: testing
    if: type = pull_request

jobs:
  include:
    - stage: testing
      if: type = pull_request
      script: npm run test
    - stage: deploy
      script: echo 'deploying'
      deploy:
        provider: script
        script: bash scripts/deploy.sh
        on:
          tags: true